<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { api, ApiError, del, post, put } from './api'
import type { Batch, Dashboard, Location, Product, ShoppingItem, TodoItem } from './types'
import { expiryText, levelText, stockSummary } from './domain'
import BarcodeScanner from './components/BarcodeScanner.vue'

type Tab='home'|'stock'|'shopping'|'todos'|'settings'
type Me={id:string;username:string;name:string;role:'platform_admin'|'owner'|'member';household_id:string;household_name?:string;must_change_password:boolean}
const loading=ref(true),loggedIn=ref(false),error=ref(''),toast=ref(''),tab=ref<Tab>('home'),me=ref<Me|null>(null)
const platform=ref<{icp_number:string}>({icp_number:''})
const dashboard=ref<Dashboard|null>(null),products=ref<Product[]>([]),batches=ref<Batch[]>([]),locations=ref<Location[]>([]),shopping=ref<ShoppingItem[]>([]),todos=ref<TodoItem[]>([])
const showProduct=ref(false),showBatch=ref(false),showShopping=ref(false),showTodo=ref(false),showScanner=ref(false)
const displayMode=location.pathname.startsWith('/display/'),displayToken=displayMode?decodeURIComponent(location.pathname.split('/').pop()||''):''
const privacyMode=location.pathname==='/privacy'
const adminPath=location.pathname==='/admin'
const registerMode=location.pathname==='/register',joinMode=location.pathname==='/join'
let displayTimer:number|undefined
const auth=reactive({username:'',password:'',display_name:'',household_name:'',code:new URLSearchParams(location.search).get('code')||'',token:new URLSearchParams(location.search).get('token')||'',current_password:'',new_password:''})
const productForm=reactive<any>({id:'',name:'',category:'',default_unit:'件',tracking_mode:'quantity',low_threshold:1,after_open_days:null,barcode:null,favorite:false})
const batchForm=reactive<any>({id:'',product_id:'',location_id:'',quantity:1,level:'enough',expiry_date:null,opened_at:null,note:'',version:0})
const shoppingForm=reactive<any>({name:'',quantity:null,unit:'件'})
const todoForm=reactive<any>({id:'',title:'',note:'',checked:false})
const settings=reactive({name:'',expiry_warning_days:7}),inviteLink=ref(''),displayLink=ref(''),sessions=ref<any[]>([]),displayTokens=ref<any[]>([]),members=ref<any[]>([])
const locationName=ref(''),stockQuery=ref(''),locationFilter=ref('')
const signupLink=ref(''),adminHouseholds=ref<any[]>([]),adminUsers=ref<any[]>([]),adminCodes=ref<any[]>([])
const filteredProducts=computed(()=>products.value.filter(p=>(!stockQuery.value||p.name.includes(stockQuery.value)||p.category.includes(stockQuery.value))&&(!locationFilter.value||batches.value.some(b=>b.product_id===p.id&&b.location_id===locationFilter.value))))
function notify(s:string){toast.value=s;window.setTimeout(()=>toast.value='',2200)}
function showError(e:unknown){error.value=e instanceof Error?e.message:'操作失败';window.setTimeout(()=>error.value='',4000)}
async function boot(){if(displayMode){await loadDisplay();loading.value=false;displayTimer=window.setInterval(loadDisplay,300000);return}try{platform.value=await api('/status')}catch{}if(privacyMode||registerMode||joinMode){loading.value=false;return}await getMe();loading.value=false}
async function getMe(){try{const current=await api<Me>('/me');if(adminPath&&current.role!=='platform_admin'){await post('/auth/logout');throw new Error('该账号没有平台管理权限')};me.value=current;loggedIn.value=true;if(current.role==='platform_admin')await loadAdmin();else if(!current.must_change_password)await loadAll()}catch(e){if(!(e instanceof ApiError&&e.status===401))showError(e);loggedIn.value=false}}
async function login(){try{await post('/auth/login',{username:auth.username,password:auth.password});await getMe()}catch(e){showError(e)}}
async function register(){try{await post('/register',{code:auth.code,username:auth.username,password:auth.password,display_name:auth.display_name,household_name:auth.household_name});history.replaceState({},'',location.origin+'/');await getMe()}catch(e){showError(e)}}
async function join(){try{await post('/household-invites/'+encodeURIComponent(auth.token)+'/accept',{username:auth.username,password:auth.password,display_name:auth.display_name});history.replaceState({},'',location.origin+'/');await getMe()}catch(e){showError(e)}}
async function changePassword(){try{await post('/auth/change-password',{current_password:auth.current_password,new_password:auth.new_password});auth.current_password='';auth.new_password='';await getMe();notify('密码已修改')}catch(e){showError(e)}}
async function logout(){await post('/auth/logout');if('caches'in window){for(const key of await caches.keys())await caches.delete(key)};loggedIn.value=false;me.value=null;location.href='/'}
async function loadAll(){await Promise.all([loadDashboard(),loadProducts(),loadBatches(),loadLocations(),loadShopping(),loadTodos()])}
async function loadDashboard(){dashboard.value=await api('/dashboard')}
async function loadProducts(){products.value=await api('/products/')}
async function loadBatches(){batches.value=await api('/batches/')}
async function loadLocations(){locations.value=await api('/locations/')}
async function loadShopping(){shopping.value=await api('/shopping/?all=1')}
async function loadTodos(){todos.value=await api('/todos/?all=1')}
async function loadDisplay(){try{dashboard.value=await api('/display/'+displayToken)}catch(e){showError(e)}}
function newProduct(barcode:string|null=null){Object.assign(productForm,{id:'',name:'',category:'',default_unit:'件',tracking_mode:'quantity',low_threshold:1,after_open_days:null,barcode,favorite:false});showProduct.value=true}
function editProduct(p:Product){Object.assign(productForm,p);showProduct.value=true}
async function saveProduct(){try{const body={...productForm,low_threshold:productForm.tracking_mode==='quantity'&&productForm.low_threshold!==''?Number(productForm.low_threshold):null,after_open_days:productForm.after_open_days===''?null:Number(productForm.after_open_days)||null};if(body.id)await put('/products/'+body.id,body);else await post('/products/',body);showProduct.value=false;await loadAll();notify('商品已保存')}catch(e){showError(e)}}
async function removeProduct(){if(!confirm('删除商品及其全部库存？'))return;try{await del('/products/'+productForm.id);showProduct.value=false;await loadAll()}catch(e){showError(e)}}
function newBatch(productId=''){const p=products.value.find(x=>x.id===productId);Object.assign(batchForm,{id:'',product_id:productId||products.value[0]?.id||'',location_id:locations.value[0]?.id||'',quantity:1,level:'enough',expiry_date:null,opened_at:null,note:'',version:0});if(p?.tracking_mode==='level')batchForm.quantity=null;showBatch.value=true}
function editBatch(b:Batch){Object.assign(batchForm,b);showBatch.value=true}
async function saveBatch(){try{const p=products.value.find(x=>x.id===batchForm.product_id);const body={...batchForm,quantity:p?.tracking_mode==='quantity'?Number(batchForm.quantity):null,level:p?.tracking_mode==='level'?batchForm.level:null,expiry_date:batchForm.expiry_date||null,opened_at:batchForm.opened_at||null};if(body.id)await put('/batches/'+body.id,body);else await post('/batches/',body);showBatch.value=false;await loadAll();notify('库存已保存')}catch(e){showError(e)}}
async function removeBatch(){if(!confirm('删除这批库存？'))return;try{await del(`/batches/${batchForm.id}?version=${batchForm.version}`);showBatch.value=false;await loadAll()}catch(e){showError(e)}}
async function adjust(b:Batch,delta?:number,level?:string){try{await post(`/batches/${b.id}/adjust`,{delta,level,version:b.version});await loadAll()}catch(e){showError(e)}}
async function openBatch(b:Batch){try{await post(`/batches/${b.id}/open`,{});await loadAll();notify('已标记开封')}catch(e){showError(e)}}
async function addToShopping(p:Product){try{await post('/shopping/from-product/'+p.id);await Promise.all([loadShopping(),loadDashboard()]);notify('已加入采购清单')}catch(e){showError(e)}}
async function addShopping(){try{await post('/shopping/',{...shoppingForm,quantity:shoppingForm.quantity?Number(shoppingForm.quantity):null});showShopping.value=false;shoppingForm.name='';shoppingForm.quantity=null;await loadShopping()}catch(e){showError(e)}}
async function toggleShopping(i:ShoppingItem){try{await put('/shopping/'+i.id,{...i,checked:!i.checked});await Promise.all([loadShopping(),loadDashboard()])}catch(e){showError(e)}}
async function removeShopping(i:ShoppingItem){await del('/shopping/'+i.id);await loadShopping()}
function newTodo(){Object.assign(todoForm,{id:'',title:'',note:'',checked:false});showTodo.value=true}
function editTodo(i:TodoItem){Object.assign(todoForm,i);showTodo.value=true}
async function saveTodo(){try{const body={...todoForm};if(body.id)await put('/todos/'+body.id,body);else await post('/todos/',body);showTodo.value=false;await Promise.all([loadTodos(),loadDashboard()]);notify('待办已保存')}catch(e){showError(e)}}
async function toggleTodo(i:TodoItem){try{await put('/todos/'+i.id,{...i,checked:!i.checked});await Promise.all([loadTodos(),loadDashboard()])}catch(e){showError(e)}}
async function removeTodo(){if(!confirm('删除这条待办？'))return;try{await del('/todos/'+todoForm.id);showTodo.value=false;await Promise.all([loadTodos(),loadDashboard()])}catch(e){showError(e)}}
async function undo(){const event=dashboard.value?.recent_event;if(!event)return;try{await post('/events/'+event.id+'/undo');await loadAll();notify('已撤销最近操作')}catch(e){showError(e)}}
async function scanned(code:string){showScanner.value=false;try{const p=await api<Product>('/products/barcode/'+encodeURIComponent(code));newBatch(p.id)}catch(e){if(e instanceof ApiError&&e.status===404)newProduct(code);else showError(e)}}
async function openSettings(){tab.value='settings';try{Object.assign(settings,await api('/settings'));sessions.value=await api('/sessions');members.value=await api('/members');if(me.value?.role==='owner')displayTokens.value=await api('/display-tokens')}catch(e){showError(e)}}
async function saveSettings(){try{await put('/settings',settings);if(me.value)me.value.household_name=settings.name;notify('设置已保存')}catch(e){showError(e)}}
async function createInvite(){try{const x=await post<any>('/household-invites');inviteLink.value=`${location.origin}/join?token=${x.token}`}catch(e){showError(e)}}
async function createDisplay(){try{const x=await post<any>('/display-tokens',{name:'Kindle'});displayLink.value=`${location.origin}/display/${x.token}`;displayTokens.value=await api('/display-tokens')}catch(e){showError(e)}}
async function removeMember(id:string){if(!confirm('移除这位家庭成员并注销其设备？'))return;await del('/members/'+id);await openSettings()}
async function copy(value:string){await navigator.clipboard.writeText(value);notify('链接已复制')}
async function addLocation(){if(!locationName.value.trim())return;try{await post('/locations/',{name:locationName.value,sort_order:locations.value.length});locationName.value='';await loadLocations()}catch(e){showError(e)}}
async function loadAdmin(){[adminHouseholds.value,adminUsers.value,adminCodes.value]=await Promise.all([api<any[]>('/admin/households'),api<any[]>('/admin/users'),api<any[]>('/admin/signup-codes')])}
async function createSignupCode(){try{const x=await post<any>('/admin/signup-codes');signupLink.value=`${location.origin}/register?code=${x.token}`;await loadAdmin()}catch(e){showError(e)}}
async function setHouseholdStatus(h:any){try{await put('/admin/households/'+h.id+'/status',{status:h.status==='active'?'suspended':'active'});await loadAdmin()}catch(e){showError(e)}}
async function resetUser(u:any){const password=prompt(`为 ${u.username} 设置临时密码（至少 1 个字符）`);if(!password)return;try{await post('/admin/users/'+u.id+'/reset-password',{temporary_password:password});notify('临时密码已设置');await loadAdmin()}catch(e){showError(e)}}
onMounted(boot);onBeforeUnmount(()=>displayTimer&&clearInterval(displayTimer))
</script>

<template>
  <div v-if="loading" class="center-page"><div class="loader"></div><p>正在打开 EatBy…</p></div>
  <main v-else-if="privacyMode" class="privacy-page"><article><a href="/">← 返回 EatBy</a><h1>隐私说明</h1><p>EatBy 仅保存你主动填写的用户名、家庭成员称呼、食材库存、采购清单和设备会话信息，用于向家庭成员提供服务。</p><p>不同家庭的数据通过家庭标识隔离。平台管理员可以查看家庭和账号运行状态，但管理界面不会展示具体食材内容。</p><p>我们不会出售数据，也不会接入广告追踪。服务器会通过加密连接提供服务，并生成数据库备份用于故障恢复。</p><p>如需停用账号、删除家庭数据或导出数据，请联系平台管理员。</p></article></main>
  <main v-else-if="displayMode" class="kindle"><header><div><h1>家庭食材看板</h1><p>更新于 {{new Date(dashboard?.generated_at||'').toLocaleString('zh-CN',{hour12:false})}}</p></div><div class="kindle-count">库存 {{dashboard?.stock_count||0}} 批</div></header><div v-if="error" class="kindle-error">{{error}} · 正在显示最后一次数据</div><section class="kindle-grid"><article><h2>临期 / 已过期</h2><p v-if="!dashboard?.expired.length&&!dashboard?.expiring.length" class="kindle-empty">暂无临期食材</p><div v-for="b in [...(dashboard?.expired||[]),...(dashboard?.expiring||[])]" :key="b.id" class="kindle-row"><strong>{{b.product_name}}</strong><span>{{b.effective_expiry}} · {{b.location_name}}</span></div></article><article><h2>快没了</h2><p v-if="!dashboard?.low_stock.length" class="kindle-empty">库存充足</p><div v-for="p in dashboard?.low_stock" :key="p.id" class="kindle-row"><strong>{{p.name}}</strong><span>{{stockSummary(p)}}</span></div></article><article><h2>采购清单</h2><p v-if="!dashboard?.shopping.length" class="kindle-empty">采购清单为空</p><div v-for="i in dashboard?.shopping" :key="i.id" class="kindle-row"><strong>□ {{i.name}}</strong><span>{{i.quantity?`${i.quantity} ${i.unit||''}`:''}}</span></div></article><article><h2>代办清单</h2><p v-if="!dashboard?.todos.length" class="kindle-empty">暂无待办事项</p><div v-for="i in dashboard?.todos" :key="i.id" class="kindle-row"><strong>□ {{i.title}}</strong><span>{{i.note}}</span></div></article></section></main>

  <div v-else-if="!loggedIn" class="auth-page"><section class="auth-card"><div class="brand-mark">食</div><h1>{{registerMode?'创建独立家庭':joinMode?'加入家庭':'登录 EatBy'}}</h1><p class="muted">{{registerMode?'使用朋友给你的平台邀请码创建家庭。':joinMode?'每位成员都有自己的账号和密码。':'管理食材、保质期和采购清单。'}}</p><label v-if="registerMode">家庭名称<input v-model="auth.household_name" placeholder="例如：小林家"></label><label v-if="registerMode||joinMode">你的称呼<input v-model="auth.display_name" placeholder="例如：小林"></label><label>用户名<input v-model="auth.username" autocomplete="username" placeholder="3-32 位字母、数字或 _.-"></label><label>密码<input v-model="auth.password" type="password" autocomplete="current-password" placeholder="至少 1 个字符"></label><button class="primary wide" @click="registerMode?register():joinMode?join():login()">{{registerMode?'创建家庭':joinMode?'加入家庭':'登录'}}</button><p v-if="registerMode||joinMode" class="muted"><a href="/">返回登录</a></p></section></div>

  <div v-else-if="me?.must_change_password" class="auth-page"><section class="auth-card"><div class="brand-mark">钥</div><h1>修改临时密码</h1><p class="muted">管理员重置过你的密码，请先换成自己的密码。</p><label>当前临时密码<input v-model="auth.current_password" type="password"></label><label>新密码<input v-model="auth.new_password" type="password" placeholder="至少 1 个字符"></label><button class="primary wide" @click="changePassword">修改密码</button><button class="danger-link wide" @click="logout">退出登录</button></section></div>

  <div v-else-if="me?.role==='platform_admin'" class="app-shell"><header class="topbar"><div><p class="eyebrow">EatBy 平台</p><h1>管理后台</h1></div><button @click="logout">退出</button></header><main class="content admin-grid"><section class="settings-card"><h2>邀请新家庭</h2><p class="muted">邀请码 7 天有效，只能创建一个家庭。</p><button class="primary" @click="createSignupCode">生成注册链接</button><div v-if="signupLink" class="link-box"><input :value="signupLink" readonly><button @click="copy(signupLink)">复制</button></div><p class="muted">已生成 {{adminCodes.length}} 个邀请码</p></section><section class="settings-card admin-wide"><h2>家庭</h2><p v-if="!adminHouseholds.length" class="empty">暂无家庭</p><p v-for="h in adminHouseholds" :key="h.id" class="device-row"><span><strong>{{h.name}}</strong><small>{{h.user_count}} 人 · {{h.batch_count}} 批 · {{h.status==='active'?'正常':'已暂停'}}</small></span><button @click="setHouseholdStatus(h)">{{h.status==='active'?'暂停':'恢复'}}</button></p></section><section class="settings-card admin-wide"><h2>用户</h2><p v-for="u in adminUsers.filter(x=>x.role!=='platform_admin')" :key="u.id" class="device-row"><span><strong>{{u.display_name}}</strong><small>@{{u.username}} · {{u.role==='owner'?'户主':'成员'}}{{u.must_change_password?' · 待改密':''}}</small></span><button @click="resetUser(u)">重置密码</button></p></section></main></div>

  <div v-else class="app-shell"><header class="topbar"><div><p class="eyebrow">{{me?.household_name}}</p><h1>{{tab==='home'?'今天家里有什么':tab==='stock'?'全部库存':tab==='shopping'?'采购清单':tab==='todos'?'代办清单':'家庭设置'}}</h1></div><button v-if="tab==='stock'" class="scan-button" @click="showScanner=true">▣ 扫码</button></header><main class="content">
    <template v-if="tab==='home'"><section class="hero"><div><p>共记录</p><strong>{{dashboard?.stock_count||0}}</strong><span>批库存</span></div><button v-if="dashboard?.recent_event" class="ghost" @click="undo">↶ 撤销最近操作</button></section><section v-if="dashboard?.expired.length" class="section"><div class="section-title"><h2>已经过期</h2><span class="badge danger">{{dashboard.expired.length}}</span></div><div class="cards"><button v-for="b in dashboard.expired" :key="b.id" class="item-card warning" @click="editBatch(b)"><div><strong>{{b.product_name}}</strong><p>{{b.location_name}} · {{expiryText(b)}}</p></div><span>处理 ›</span></button></div></section><section class="section"><div class="section-title"><h2>{{dashboard?.warning_days}} 天内到期</h2><span class="badge">{{dashboard?.expiring.length||0}}</span></div><p v-if="!dashboard?.expiring.length" class="empty">近期没有要到期的食材。</p><div class="cards"><button v-for="b in dashboard?.expiring" :key="b.id" class="item-card" @click="editBatch(b)"><div><strong>{{b.product_name}}</strong><p>{{b.location_name}} · {{expiryText(b)}}</p></div><span>›</span></button></div></section><section class="section"><div class="section-title"><h2>快没了</h2><span class="badge">{{dashboard?.low_stock.length||0}}</span></div><p v-if="!dashboard?.low_stock.length" class="empty">当前库存充足。</p><div class="chips"><button v-for="p in dashboard?.low_stock" :key="p.id" @click="addToShopping(p)"><b>{{p.name}}</b><span>＋采购</span></button></div></section><section class="section"><div class="section-title"><h2>按位置查看</h2></div><div class="location-grid"><button v-for="l in dashboard?.locations" :key="l.id" @click="tab='stock';locationFilter=l.id"><strong>{{l.name}}</strong><span>{{l.count}} 批</span></button></div></section></template>
    <template v-else-if="tab==='stock'"><div class="toolbar"><input v-model="stockQuery" placeholder="搜索食材"><select v-model="locationFilter"><option value="">全部位置</option><option v-for="l in locations" :key="l.id" :value="l.id">{{l.name}}</option></select></div><p v-if="!filteredProducts.length" class="empty large">还没有食材。先添加一个常用商品。</p><section v-for="p in filteredProducts" :key="p.id" class="product-block"><div class="product-head"><button @click="editProduct(p)"><strong>{{p.favorite?'★ ':''}}{{p.name}}</strong><span>{{p.category||'未分类'}} · {{stockSummary(p)}}</span></button><button class="small primary" @click="newBatch(p.id)">＋入库</button></div><div class="batch-row" v-for="b in batches.filter(x=>x.product_id===p.id)" :key="b.id"><button class="batch-main" @click="editBatch(b)"><span>{{b.location_name}}</span><b>{{b.quantity!==null?`${b.quantity} ${b.unit}`:levelText(b.level)}}</b><small :class="b.expiry_status">{{expiryText(b)}}</small></button><div class="quick"><button v-if="b.quantity!==null" @click="adjust(b,-1)">−1</button><button v-if="b.quantity!==null" @click="adjust(b,1)">＋1</button><button v-if="!b.opened_at" @click="openBatch(b)">开封</button></div></div></section><button class="fab" @click="newProduct()">＋</button></template>
    <template v-else-if="tab==='shopping'"><div class="shopping-list"><label v-for="i in shopping" :key="i.id" :class="{checked:i.checked}"><input type="checkbox" :checked="i.checked" @change="toggleShopping(i)"><span><strong>{{i.name}}</strong><small v-if="i.quantity">{{i.quantity}} {{i.unit}}</small></span><button @click.prevent="removeShopping(i)">×</button></label></div><p v-if="!shopping.length" class="empty large">采购清单是空的。</p><button class="fab" @click="showShopping=true">＋</button></template>
    <template v-else-if="tab==='todos'"><div class="shopping-list"><label v-for="i in todos" :key="i.id" :class="{checked:i.checked}" @dblclick="editTodo(i)"><input type="checkbox" :checked="i.checked" @change="toggleTodo(i)"><span><strong>{{i.title}}</strong><small v-if="i.note">{{i.note}}</small></span><button @click.prevent="editTodo(i)">编辑</button></label></div><p v-if="!todos.length" class="empty large">待办清单是空的。</p><button class="fab" @click="newTodo">＋</button></template>
    <template v-else><section v-if="me?.role==='owner'" class="settings-card"><h2>家庭设置</h2><label>家庭名称<input v-model="settings.name"></label><label>提前提醒天数<input v-model.number="settings.expiry_warning_days" type="number" min="1" max="90"></label><button class="primary" @click="saveSettings">保存设置</button></section><section class="settings-card"><h2>家庭成员</h2><p v-for="m in members" :key="m.id" class="device-row"><span><strong>{{m.display_name}}</strong><small>@{{m.username}} · {{m.role==='owner'?'户主':'成员'}}</small></span><button v-if="me?.role==='owner'&&m.role==='member'" @click="removeMember(m.id)">移除</button></p><template v-if="me?.role==='owner'"><button @click="createInvite">生成成员邀请链接</button><div v-if="inviteLink" class="link-box"><input :value="inviteLink" readonly><button @click="copy(inviteLink)">复制</button></div></template></section><section class="settings-card"><h2>存放位置</h2><div class="tag-list"><span v-for="l in locations" :key="l.id">{{l.name}}</span></div><div class="inline-form"><input v-model="locationName" placeholder="新增位置"><button @click="addLocation">添加</button></div></section><section v-if="me?.role==='owner'" class="settings-card"><h2>Kindle 看板</h2><button @click="createDisplay">生成只读链接</button><div v-if="displayLink" class="link-box"><input :value="displayLink" readonly><button @click="copy(displayLink)">复制</button></div><p v-for="t in displayTokens" :key="t.id" class="device-row">{{t.name}}<button @click="del('/display-tokens/'+t.id).then(openSettings)">撤销</button></p></section><section class="settings-card"><h2>已登录设备</h2><p v-for="s in sessions" :key="s.id" class="device-row"><span>{{s.display_name}} · @{{s.username}}</span><button @click="del('/sessions/'+s.id).then(openSettings)">撤销</button></p></section><button class="danger-link" @click="logout">退出当前设备</button></template>
  </main><nav class="bottom-nav"><button :class="{active:tab==='home'}" @click="tab='home';loadDashboard()"><span>⌂</span>首页</button><button :class="{active:tab==='stock'}" @click="tab='stock'"><span>▤</span>库存</button><button :class="{active:tab==='shopping'}" @click="tab='shopping'"><span>✓</span>采购</button><button :class="{active:tab==='todos'}" @click="tab='todos';loadTodos()"><span>☑</span>待办</button><button :class="{active:tab==='settings'}" @click="openSettings"><span>⚙</span>设置</button></nav></div>

  <div v-if="error&&!displayMode" class="toast error-toast">{{error}}</div><div v-if="toast" class="toast">{{toast}}</div><BarcodeScanner v-if="showScanner" @found="scanned" @close="showScanner=false"/>
  <div v-if="showProduct" class="modal shade"><form class="modal-card" @submit.prevent="saveProduct"><div class="modal-head"><h3>{{productForm.id?'编辑商品':'添加商品'}}</h3><button type="button" class="icon" @click="showProduct=false">×</button></div><label>名称<input v-model="productForm.name" required autofocus></label><div class="form-grid"><label>分类<input v-model="productForm.category" placeholder="乳制品"></label><label>默认单位<input v-model="productForm.default_unit" placeholder="瓶"></label></div><label>记录方式<select v-model="productForm.tracking_mode"><option value="quantity">记录具体数量</option><option value="level">记录充足 / 快没了</option></select></label><label v-if="productForm.tracking_mode==='quantity'">低于多少算快没了<input v-model="productForm.low_threshold" type="number" step="0.1" min="0"></label><label>开封后建议天数<input v-model="productForm.after_open_days" type="number" min="1" placeholder="可不填"></label><label>商品条码<input v-model="productForm.barcode" placeholder="可扫码或手动填写"></label><label class="checkbox"><input v-model="productForm.favorite" type="checkbox">设为常用商品</label><button class="primary wide">保存商品</button><button v-if="productForm.id" type="button" class="danger-link" @click="removeProduct">删除商品</button></form></div>
  <div v-if="showBatch" class="modal shade"><form class="modal-card" @submit.prevent="saveBatch"><div class="modal-head"><h3>{{batchForm.id?'编辑库存':'添加库存'}}</h3><button type="button" class="icon" @click="showBatch=false">×</button></div><label>商品<select v-model="batchForm.product_id" required><option v-for="p in products" :key="p.id" :value="p.id">{{p.name}}</option></select></label><label>存放位置<select v-model="batchForm.location_id" required><option v-for="l in locations" :key="l.id" :value="l.id">{{l.name}}</option></select></label><label v-if="products.find(p=>p.id===batchForm.product_id)?.tracking_mode==='quantity'">数量<input v-model="batchForm.quantity" type="number" min="0" step="0.1" required></label><label v-else>当前状态<select v-model="batchForm.level"><option value="enough">充足</option><option value="half">一半</option><option value="low">快没了</option><option value="empty">用完</option></select></label><label>包装到期日<input v-model="batchForm.expiry_date" type="date"></label><label>备注<input v-model="batchForm.note"></label><button class="primary wide">保存库存</button><button v-if="batchForm.id" type="button" class="danger-link" @click="removeBatch">删除这批库存</button></form></div>
  <div v-if="showShopping" class="modal shade"><form class="modal-card" @submit.prevent="addShopping"><div class="modal-head"><h3>添加采购项</h3><button type="button" class="icon" @click="showShopping=false">×</button></div><label>名称<input v-model="shoppingForm.name" required autofocus></label><div class="form-grid"><label>数量<input v-model="shoppingForm.quantity" type="number" min="0" step="0.1"></label><label>单位<input v-model="shoppingForm.unit"></label></div><button class="primary wide">加入清单</button></form></div>
  <div v-if="showTodo" class="modal shade"><form class="modal-card" @submit.prevent="saveTodo"><div class="modal-head"><h3>{{todoForm.id?'编辑待办':'添加待办'}}</h3><button type="button" class="icon" @click="showTodo=false">×</button></div><label>事项<input v-model="todoForm.title" required autofocus placeholder="例如：周末买猫砂"></label><label>备注<input v-model="todoForm.note" placeholder="可不填"></label><label class="checkbox"><input v-model="todoForm.checked" type="checkbox">已完成</label><button class="primary wide">保存待办</button><button v-if="todoForm.id" type="button" class="danger-link" @click="removeTodo">删除待办</button></form></div>
  <footer v-if="!displayMode&&!privacyMode" class="site-footer"><a href="/privacy">隐私说明</a><span v-if="platform.icp_number">{{platform.icp_number}}</span></footer>
</template>
